/** @type {import("tailwindcss").Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#000767",
        "inverse-surface": "#2e3132",
        "tertiary-fixed": "#ffdbd0",
        "surface-container-high": "#e7e8e9",
        "primary-container": "#1a237e",
        "on-surface": "#191c1d",
        "surface-variant": "#e1e3e4",
        "on-surface-variant": "#454652",
        "primary-fixed": "#e0e0ff",
        "on-primary-fixed-variant": "#343d96",
        "on-secondary-container": "#007166",
        "surface-dim": "#d9dadb",
        "inverse-on-surface": "#f0f1f2",
        "surface-bright": "#f8f9fa",
        "secondary-fixed-dim": "#67d9c9",
        "secondary-fixed": "#85f6e5",
        "on-secondary": "#ffffff",
        "surface-container": "#edeeef",
        "inverse-primary": "#bdc2ff",
        "tertiary-fixed-dim": "#ffb59d",
        "secondary-container": "#85f6e5",
        background: "#f8f9fa",
        "on-background": "#191c1d",
        "outline-variant": "#c6c5d4",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#390c00",
        secondary: "#006a60",
        "on-secondary-fixed": "#00201c",
        "on-error-container": "#93000a",
        "surface-tint": "#4c56af",
        "on-tertiary-container": "#e17c5a",
        primary: "#000666",
        "surface-container-low": "#f3f4f5",
        tertiary: "#380b00",
        surface: "#f8f9fa",
        "tertiary-container": "#5c1800",
        "on-tertiary-fixed-variant": "#7b2e12",
        "on-primary-container": "#8690ee",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#005048",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        outline: "#767683",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#bdc2ff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        curator: "0 20px 40px rgba(25, 28, 29, 0.05)",
      },
    },
  },
  plugins: [],
};

